/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import conexion.Conexion;
import controlador.Coleccion;
import modelo.Pelicula;


/**
 *
 * @author Bababooey
 */
public class Menu extends javax.swing.JFrame {
    Coleccion col = new Coleccion();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        col = new Coleccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        TAGREGAR = new javax.swing.JToggleButton();
        TMODIFICAR = new javax.swing.JToggleButton();
        TELIMINAR = new javax.swing.JToggleButton();
        TLISTAR = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        TAGREGAR.setText("AGREGAR");
        TAGREGAR.setFocusable(false);
        TAGREGAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TAGREGAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAGREGARActionPerformed(evt);
            }
        });
        jToolBar1.add(TAGREGAR);

        TMODIFICAR.setText("MODIFICAR");
        TMODIFICAR.setFocusable(false);
        TMODIFICAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TMODIFICAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMODIFICARActionPerformed(evt);
            }
        });
        jToolBar1.add(TMODIFICAR);

        TELIMINAR.setText("ELIMINAR");
        TELIMINAR.setFocusable(false);
        TELIMINAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TELIMINAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TELIMINARActionPerformed(evt);
            }
        });
        jToolBar1.add(TELIMINAR);

        TLISTAR.setText("LISTAR");
        TLISTAR.setFocusable(false);
        TLISTAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TLISTAR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TLISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLISTARActionPerformed(evt);
            }
        });
        jToolBar1.add(TLISTAR);

        jLabel1.setText("HoytsMarkPlanet");

        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(SALIR))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(SALIR)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void TAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAGREGARActionPerformed
        // TODO add your handling code here:
           
           AgregarMenu objeto = new AgregarMenu();
           objeto.setVisible(true);

    }//GEN-LAST:event_TAGREGARActionPerformed

    private void TMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMODIFICARActionPerformed
        // TODO add your handling code here:
        ModificarMenu objeto = new ModificarMenu();
           objeto.setVisible(true);
    }//GEN-LAST:event_TMODIFICARActionPerformed

    private void TELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TELIMINARActionPerformed
        // TODO add your handling code here:
        EliminarMenu objeto = new EliminarMenu();
           objeto.setVisible(true);
    }//GEN-LAST:event_TELIMINARActionPerformed

    private void TLISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLISTARActionPerformed
        // TODO add your handling code here:
        ListarMenu objeto = new ListarMenu();
           objeto.setVisible(true);
    }//GEN-LAST:event_TLISTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SALIR;
    private javax.swing.JToggleButton TAGREGAR;
    private javax.swing.JToggleButton TELIMINAR;
    private javax.swing.JToggleButton TLISTAR;
    private javax.swing.JToggleButton TMODIFICAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
